#!/bin/bash
export PATH="/home/soft/ORCA:$PATH"
export PATH="/usr/lib64/openmpi/bin:$PATH"
export LD_LIBRARY_PATH="/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH"
export OMPI_MCA_hwloc_base_use_hwthreads_as_cpus=1

input_name=$1
output_name="${input_name%.*}.out"

/home/soft/ORCA/orca $input_name > $output_name
